# Automatically generated by Pynguin.
import ansible.plugins.action.fail as module_0

def test_case_0():
    try:
        set_0 = set()
        int_0 = 50
        list_0 = [set_0, set_0, int_0, int_0]
        bool_0 = False
        action_module_0 = module_0.ActionModule(set_0, int_0, int_0, list_0, bool_0, set_0)
        var_0 = action_module_0.run()
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = -2276
        bool_0 = False
        list_0 = [int_0, int_0, bool_0]
        bytes_0 = b'\x07\xd2\xd3\x97\xb4\x04b\t.X\xb8\xe7C\xfd'
        str_0 = '.crt'
        str_1 = '_ansible_loop_cache'
        action_module_0 = module_0.ActionModule(int_0, bool_0, list_0, bytes_0, str_0, str_1)
        str_2 = 'a>5Qn{'
        bool_1 = False
        float_0 = -654.0
        dict_0 = {str_2: str_2, float_0: float_0}
        str_3 = "\n        Loads all available callbacks, with the exception of those which\n        utilize the CALLBACK_TYPE option. When CALLBACK_TYPE is set to 'stdout',\n        only one such callback plugin will be loaded.\n        "
        int_1 = 1514
        tuple_0 = (str_3, int_1)
        float_1 = None
        set_0 = {bool_1, tuple_0, bool_1, float_1}
        action_module_1 = module_0.ActionModule(str_2, bool_1, dict_0, str_2, tuple_0, set_0)
        var_0 = action_module_1.run(int_0, action_module_0)
    except BaseException:
        pass